version: '3.7'

services:
  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - default

networks:
  default:
    name: memcached